site_name: Quattor Configuration Modules (Core)

theme: 'readthedocs'

pages:
- ['index.md', 'introduction']
- ['components/accounts.md', 'components']
- ['components/afsclt.md', 'components']
- ['components/aiiserver.md', 'components']
- ['components/altlogrotate.md', 'components']
- ['components/amandaserver.md', 'components']
- ['components/authconfig.md', 'components']
- ['components/autofs.md', 'components']
- ['components/ccm.md', 'components']
- ['components/cdp.md', 'components']
- ['components/ceph.md', 'components']
- ['components/ceph::commands.md', 'components']
- ['components/ceph::compare.md', 'components']
- ['components/ceph::config.md', 'components']
- ['components/ceph::crushmap.md', 'components']
- ['components/ceph::daemon.md', 'components']
- ['components/chkconfig.md', 'components']
- ['components/cron.md', 'components']
- ['components/cups.md', 'components']
- ['components/directoryservices.md', 'components']
- ['components/dirperm.md', 'components']
- ['components/download.md', 'components']
- ['components/etcservices.md', 'components']
- ['components/filecopy.md', 'components']
- ['components/filesystems.md', 'components']
- ['components/fmonagent.md', 'components']
- ['components/fsprobe.md', 'components']
- ['components/fstab.md', 'components']
- ['components/ganglia.md', 'components']
- ['components/gmetad.md', 'components']
- ['components/gmond.md', 'components']
- ['components/gpfs.md', 'components']
- ['components/grub.md', 'components']
- ['components/hostsaccess.md', 'components']
- ['components/hostsfile.md', 'components']
- ['components/icinga.md', 'components']
- ['components/interactivelimits.md', 'components']
- ['components/ipmi.md', 'components']
- ['components/iptables.md', 'components']
- ['components/ldconf.md', 'components']
- ['components/libvirtd.md', 'components']
- ['components/mcx.md', 'components']
- ['components/metaconfig.md', 'components']
- ['components/modprobe.md', 'components']
- ['components/mysql.md', 'components']
- ['components/nagios.md', 'components']
- ['components/named.md', 'components']
- ['components/network.md', 'components']
- ['components/nfs.md', 'components']
- ['components/nrpe.md', 'components']
- ['components/nsca.md', 'components']
- ['components/nscd.md', 'components']
- ['components/nss.md', 'components']
- ['components/ntpd.md', 'components']
- ['components/ofed.md', 'components']
- ['components/openldap.md', 'components']
- ['components/opennebula.md', 'components']
- ['components/opennebula::commands.md', 'components']
- ['components/openvpn.md', 'components']
- ['components/pam.md', 'components']
- ['components/pnp4nagios.md', 'components']
- ['components/postfix.md', 'components']
- ['components/postgresql.md', 'components']
- ['components/profile.md', 'components']
- ['components/puppet.md', 'components']
- ['components/resolver.md', 'components']
- ['components/sendmail.md', 'components']
- ['components/shorewall.md', 'components']
- ['components/spma.md', 'components']
- ['components/spma::ips.md', 'components']
- ['components/spma::yum.md', 'components']
- ['components/ssh.md', 'components']
- ['components/sudo.md', 'components']
- ['components/symlink.md', 'components']
- ['components/sysconfig.md', 'components']
- ['components/sysctl.md', 'components']
- ['components/syslog.md', 'components']
- ['components/syslogng.md', 'components']
- ['components/systemd.md', 'components']
- ['components/systemd::Service.md', 'components']
- ['components/systemd::Chkconfig.md', 'components']
- ['components/systemd::chkconfig.md', 'components']
- ['components/systemd::Unit.md', 'components']
- ['components/systemd::Systemctl.md', 'components']
- ['components/useraccess.md', 'components']
